/**
 * Turns bench/results/*.json into what the docs and the README show:
 * - SVG charts in docs/public/benchmarks/ (served by the docs site, embedded
 *   by the README, where no script can render the interactive docs charts);
 * - the tables between `<!-- bench:<name>:start -->` / `:end -->` markers in
 *   README.md and docs/guide/benchmarks.md (the docs page renders the same
 *   models interactively above them).
 * Both come from bench/report/model.mjs, so a chart and its table cannot
 * disagree. Text outside the markers is never touched.
 *
 * Run: pnpm bench:report   (after pnpm bench:compare / bench --json / size:compare --json)
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const RESULTS = path.join(__dirname, 'results');
const SVG_DIR = path.join(ROOT, 'docs', 'public', 'benchmarks');
const IMAGE_BASE = 'https://kerberosjs.vercel.app/benchmarks';
const TARGETS = { readme: path.join(ROOT, 'README.md'), docs: path.join(ROOT, 'docs', 'guide', 'benchmarks.md') };
const HEADLINE = 'abac';
const GENERATED = '<!-- generated by `pnpm bench:report` from bench/results — edit the results, not this block -->';

function readResults(name) {
  try {
    return JSON.parse(fs.readFileSync(path.join(RESULTS, `${name}.json`), 'utf8'));
  } catch {
    console.warn(`bench/results/${name}.json not found — skipping its charts and tables`);
    return null;
  }
}

/** Three significant figures, thousands-separated: 779878 → "780,000". */
function approx(value) {
  const digits = Math.max(0, Math.floor(Math.log10(Math.abs(value))) + 1 - 3);
  return (Math.round(value / 10 ** digits) * 10 ** digits).toLocaleString('en-US');
}

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;
const ms = (value) => `${value.toFixed(1)} ms`;

function table(header, align, rows) {
  return [`| ${header.join(' | ')} |`, `| ${align.join(' | ')} |`, ...rows.map((row) => `| ${row.join(' | ')} |`)].join(
    '\n',
  );
}

/** `isAllowed — simple role match` → `\`isAllowed\` — simple role match`, as the hand-written tables had it. */
const codeApi = (name) => name.replace(/^([\w.]+) — /, '`$1` — ');

/** Name on the first line, the timed API and version underneath (HTML renders on GitHub, npm and VitePress). */
function libraryCell(library, engineVersion) {
  const name = library.id === 'kerberos' ? `**${library.name}**` : library.name;
  return `${name}<br><sub>${library.variant} · ${engineVersion(library)}</sub>`;
}

function image(file, alt) {
  return `<img src="${IMAGE_BASE}/${file}" alt="${alt.replace(/"/g, '&quot;')}" width="760" />`;
}

async function main() {
  const model = await import('./report/model.mjs');
  const { renderSvg } = await import('./report/svg.mjs');
  const compare = readResults('compare');
  const size = readResults('size');
  const engine = readResults('engine');

  fs.mkdirSync(SVG_DIR, { recursive: true });
  const writeSvg = (file, chart, caption) => {
    fs.writeFileSync(path.join(SVG_DIR, file), renderSvg(chart, { caption }));
    console.log(`wrote docs/public/benchmarks/${file}`);
  };

  /** name → { readme, docs } markdown */
  const regions = {};

  if (compare) {
    const caption = model.compareCaption(compare);
    // The README shows the headline scenario; the others fold into <details>
    // so four tall images do not push the tables off the screen.
    let headline = '';
    const more = [];
    for (const scenario of model.compareScenarios(compare)) {
      const chart = model.compareModel(compare, scenario.id, 'log');
      writeSvg(`compare-${scenario.id}.svg`, chart, caption);
      const img = image(`compare-${scenario.id}.svg`, `${chart.title}: ${chart.subtitle}`);
      if (scenario.id === HEADLINE) headline = img;
      else more.push({ title: scenario.title, img });
    }
    const details = [
      `<details>\n<summary>More scenarios: ${more.map((item) => item.title).join(' · ')}</summary>`,
      ...more.map((item) => item.img),
      '</details>',
    ].join('\n\n');
    const scenarios = compare.scenarios;
    const matrix = table(
      ['Library', ...scenarios.map((scenario) => `${scenario.title}<br><sub>${scenario.unit}</sub>`)],
      ['---', ...scenarios.map(() => '---:')],
      compare.libraries.map((library) => [
        libraryCell(library, model.engineVersion),
        ...scenarios.map((scenario) => {
          const result = scenario.results[library.id];
          return result ? approx(result.median) : '—';
        }),
      ]),
    );
    const note = `_${caption}. Medians, rounded to three significant figures._`;
    regions.compare = {
      readme: [headline, details, matrix, note].join('\n\n'),
      docs: [matrix, note].join('\n\n'),
    };

    const cold = model.coldStartModel(compare);
    writeSvg('coldstart.svg', cold, model.machineCaption(compare.machine));
    const coldTable = table(
      ['Library', 'Load', 'Build policy', 'First decision', 'Total'],
      ['---', '---:', '---:', '---:', '---:'],
      model.allRows(cold).map((row) => {
        const phases = compare.coldStart[row.id];
        const library = compare.libraries.find((candidate) => candidate.id === row.id);
        return [
          libraryCell(library, model.engineVersion),
          ms(phases.load),
          ms(phases.setup),
          ms(phases.firstDecision),
          ms(phases.total),
        ];
      }),
    );
    regions.coldstart = {
      readme: [image('coldstart.svg', `${cold.title}: ${cold.subtitle}`), coldTable].join('\n\n'),
      docs: coldTable,
    };
  }

  if (size) {
    const chart = model.sizeModel(size);
    writeSvg('size.svg', chart, null);
    const sizeTable = table(
      ['Library', 'min', 'min+gzip', ''],
      ['---', '---:', '---:', '---'],
      size.libraries.map((library) => {
        let note = library.browser ? '' : 'does not bundle for the browser (Node builtins) — measured as a Node bundle';
        if (library.policyWasm) {
          note = `+ ${kb(library.policyWasm.gzip)} gzip for the compiled policy (.wasm, ownership rule only)`;
        }
        const name = library.id === 'kerberos' ? `**\`${library.package}\`** (main entry)` : `\`${library.package}\``;
        return [name, kb(library.min), kb(library.gzip), note];
      }),
    );
    regions.size = {
      readme: [image('size.svg', `${chart.title}: ${chart.subtitle}`), sizeTable].join('\n\n'),
      docs: sizeTable,
    };
  }

  if (engine) {
    const release = model.latestRelease(engine);
    const hot = model.engineModel(engine);
    writeSvg('engine.svg', hot, model.machineCaption(release.machine));
    const engineTable = table(
      ['Scenario', 'ops/sec'],
      ['---', '---:'],
      release.scenarios
        .filter((scenario) => !scenario.name.startsWith('scaling — '))
        .map((scenario) => [codeApi(scenario.name), `~${approx(scenario.opsPerSec)}`]),
    );
    regions.engine = {
      readme: [image('engine.svg', `${hot.title}: ${hot.subtitle}`), engineTable].join('\n\n'),
      docs: engineTable,
    };

    const releases = model.releaseModel(engine);
    if (releases) {
      writeSvg('releases.svg', releases, model.machineCaption(release.machine));
      const before = new Map(engine.releases[releases.previous].scenarios.map((s) => [s.name, s.opsPerSec]));
      const releaseTable = table(
        ['Scenario', releases.previous, releases.current, 'Speed-up'],
        ['---', '---:', '---:', '---:'],
        model.allRows(releases).map((row) => {
          const now = release.scenarios.find((scenario) => scenario.name === row.id).opsPerSec;
          return [row.label, `~${approx(before.get(row.id))}`, `~${approx(now)}`, `×${row.value.toFixed(1)}`];
        }),
      );
      regions.releases = {
        readme: [image('releases.svg', `${releases.title}: ${releases.subtitle}`), releaseTable].join('\n\n'),
        docs: releaseTable,
      };
    }
  }

  for (const [target, file] of Object.entries(TARGETS)) {
    let text = fs.readFileSync(file, 'utf8');
    for (const [name, content] of Object.entries(regions)) {
      const start = `<!-- bench:${name}:start -->`;
      const end = `<!-- bench:${name}:end -->`;
      const from = text.indexOf(start);
      const to = text.indexOf(end);
      if (from === -1 || to === -1) continue;
      text = `${text.slice(0, from + start.length)}\n${GENERATED}\n\n${content[target]}\n\n${text.slice(to)}`;
    }
    fs.writeFileSync(file, text);
    console.log(`updated ${path.relative(ROOT, file)}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
